version: "3.4"

services:

  decort-redis:
    image: redis:latest
    container_name: decort-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - decort-redis-data:/data

  decort-db:
    image: postgis/postgis
    container_name: decort-db
    restart: always
    volumes:
      - decort-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  decort-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: decort-app
    command: bash start.sh
    env_file:
      - .env
    environment:
      WAIT-HOSTS: decort-db, decort-elastic, decort-redis
    volumes:
      - .:/home/app/
      - ../logs:/home/app/logs/
      - ./static:/home/app/static
      - ./media:/home/app/media:rw
    ports:
      - "8000:8000"
      - "8001:8001"
    tty: true
    restart: on-failure
    depends_on:
      - decort-db
      - decort-redis

  decort-elastic:
    build:
      context: _configs/elastic/
      args:
        ELK_VERSION: 7.15.1
    container_name: decort-elastic
    volumes:
      - type: bind
        source: ./_configs/elastic/elasticsearch.yml
        target: /usr/share/elasticsearch/elasticsearch.yml
        read_only: true
      - type: volume
        source: decort-elastic-data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "ELASTIC_PASSWORD=decort_elk"
      - "discovery.type=single-node"

  decort-logstash:
    build:
      context: _configs/logstash/
      args:
        ELK_VERSION: 7.15.1
    container_name: decort-logstash
    volumes:
      - type: bind
        source: ./_configs/logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./_configs/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - decort-elastic

  decort-kibana:
    build:
      context: _configs/kibana/
      args:
        ELK_VERSION: 7.15.1
    container_name: decort-kibana
    volumes:
      - type: bind
        source: ./_configs/kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - decort-elastic


volumes:
  decort-db-data:
  decort-redis-data:
  decort-elastic-data:

networks:
  default:
    external:
      name: decort-network
