# Generated by Django 3.2.9 on 2021-11-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='uploads/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Uploaded'), ('2', 'Processing'), ('3', 'Done')], default='1', max_length=255)),
                ('finish_date', models.DateTimeField(blank=True)),
                ('result', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ('upload_date',),
            },
        ),
    ]
